import { Credentials } from "./credentials.tye";
import { IDivision } from "./divisions.types";
export interface IMemberData {
  _id: string;
  freeName: string;
  email: string;
  studentId: string;
  gmailId: string;
  contact: string;
  note: string | null;
  expectedGenerationYear: string;
  discoveredDate: string | null;
  fieldOfStudy: string;
  unifiedById: string | null;
  passwordLink: string | null;
  statusDates: string | null;
  customerStatusLink: string | null;
  adminLink: string | null;
  personalStatusLink: string | null;
  shortListDescription: string | null;
  lastName: string | null;
  firstAddress: string | null;
  alternateEmail: string | null;
  profileImage: string | null;
  githubProfile: string | null;
  supportHandle: string | null;
  successions: string | null;
  skills: string[];
  historyNotes: string | null;
  password: string;
  role: "MEMBER" | "PRESIDENT" | string;
  divisionId: string;
  isEmailVerified: boolean;
  status: "ACTIVE" | "INACTIVE" | string;
  isRemovedFromDivision: boolean;
  removedFromDivisionAt: string;
  removedFromDivisionBy: string;
  divisionRemovalReason: string;
  previousDivisionId: string;
  createdAt: string;
  updatedAt: string;
  division: IDivision;
  credentials: Credentials;
}
